"""Pydantic contracts shared by every graph.

``docs/ticket-spec.md`` is the normative source for these shapes; the modules
here are its executable form.
"""

from triage.schemas.analysis import (
    AnalysisFindings,
    AnalysisKind,
    AnalysisPayloadError,
    AnalysisRequest,
    AnalysisResult,
    AnalysisStatus,
    Finding,
    Payload,
    parse_payload,
    payload_schema,
)
from triage.schemas.common import (
    Confidence,
    Feature,
    Filled,
    MaybeUnknown,
    TimeWindow,
    Unknown,
    is_unknown,
    render,
)
from triage.schemas.diagnosis import (
    AcceptanceCriterion,
    Diagnosis,
    DiagnosisDraft,
    Evidence,
    EvidenceKind,
    Impact,
    Location,
    OpenQuestion,
    RuledOut,
    Symptom,
)
from triage.schemas.hypothesis import CauseType, Hypothesis
from triage.schemas.postmortem import Postmortem
from triage.schemas.signal import Signal, SignalStatus
from triage.schemas.system_map import (
    DatabaseAccess,
    DependencyKind,
    Endpoint,
    EntryPoint,
    EntryPointKind,
    ManagedDatabase,
    ModuleMapping,
    NetworkFact,
    Observability,
    RepoSummary,
    ServiceDependency,
    ServiceEntry,
    SystemMap,
    SystemMapKind,
    TerraformModuleEntry,
    TerraformResource,
    TerraformSummary,
)
from triage.schemas.ticket import (
    DedupDecision,
    PipelineOutcome,
    ReviewVerdict,
    TicketDraft,
    TicketSection,
)

__all__ = [
    "AcceptanceCriterion",
    "AnalysisFindings",
    "AnalysisKind",
    "AnalysisPayloadError",
    "AnalysisRequest",
    "AnalysisResult",
    "AnalysisStatus",
    "CauseType",
    "Confidence",
    "DatabaseAccess",
    "DedupDecision",
    "DependencyKind",
    "Diagnosis",
    "DiagnosisDraft",
    "Endpoint",
    "EntryPoint",
    "EntryPointKind",
    "Evidence",
    "EvidenceKind",
    "Feature",
    "Filled",
    "Finding",
    "Hypothesis",
    "Impact",
    "Location",
    "ManagedDatabase",
    "MaybeUnknown",
    "ModuleMapping",
    "NetworkFact",
    "Observability",
    "OpenQuestion",
    "Payload",
    "PipelineOutcome",
    "Postmortem",
    "RepoSummary",
    "ReviewVerdict",
    "RuledOut",
    "ServiceDependency",
    "ServiceEntry",
    "Signal",
    "SignalStatus",
    "Symptom",
    "SystemMap",
    "SystemMapKind",
    "TerraformModuleEntry",
    "TerraformResource",
    "TerraformSummary",
    "TicketDraft",
    "TicketSection",
    "TimeWindow",
    "Unknown",
    "is_unknown",
    "parse_payload",
    "payload_schema",
    "render",
]
